# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89dcfb665adf704ffd9ccd947eb25bbfb7cea18edd3e21755b520755fd199f84b7eb3d4149ca117d9475d7c38aea9f6fd2ee5aa3f972ff00d5257d4fa370968c

test:
  secret_key_base: 99720e01fdf9910664d799c8c05f9a535c691595e2c8bd37bf2bb78d14ff2edded8677b8d203f75a3fded7bddd161ef3b9458b1a19ae8158c9ed29517248b564

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
